---

- name: Dockerに必要なパッケージを入れる
  become: yes
  yum:
    name:
      - yum-utils
    update_cache: yes

- name: check docker-ce.repo
  stat:
    path: /etc/yum.repos.d/docker-ce.repo
  register: docker_ce_repo

- name: Add docker yum repo
  become: yes
  command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  when: docker_ce_repo.stat.exists == false

- name: Dockerをインストール
  become: yes
  yum:
    name:
      - docker-ce
